### ISSUE TITLE
Feature Request - Pause Play hotkey

### ISSUE THREAD

**Issue by bartduisters** [keshavbhatt/olivia#100]
Have the ability to configure a hotkey to toggle Play/Pause. Or have a hardcoded option that hitting Space pauses/plays the current song.

**Comment by keshavbhatt** [comment]
Pause/Play : Spacebar
Stop : S
Mute : M
Next : Ctrl+right and ,
Previous : Ctrl+left and .
seekForward : right arrow
seekBackward : left arrow
VolumeUp : 0 (zero)
VolumeDown : 9
Quit App : Ctrl+Q

**Comment by keshavbhatt** [comment]
Todo: This all need to exposed to user in the GUI.
