### ISSUE TITLE
Is this program a fork of orange-app?

### ISSUE THREAD

**Issue by lhorace** [keshavbhatt/olivia#102]
Hello,

I'm just curious, this project doesn't seem to be forked, but the behavior seem to be the same as orange-app, which asks to pay?

Regards.

**Comment by keshavbhatt** [comment]
Olivia does more than what orange-app does. Orange-app is focused on downloading playing soundcloud audios in different formats and quality. Olivia have a section for soundcloud search/download and play (which uses soundcloud public api to fetch metadata).

**Comment by keshavbhatt** [comment]
Find more details in readme of both projects.

**Comment by lhorace** [comment]
Thanks, neither problem is what I was looking for. I wanted to login, see my liked songs, and let soundcloud alco, pink my next song. Thanks for answering!
