### ISSUE TITLE
Olivia won't start - Manjaro Linux / snap

### ISSUE THREAD

**Issue by AlexD2548** [keshavbhatt/olivia#105]
Hey, 

I'd love to try your app but it won't launch. Is there a way to give your more info about the issue?

**Comment by keshavbhatt** [comment]
Can you provide the command-line output of Olivia ?

**Comment by AndreiBiziuk** [comment]
OS - Arch linux
Olivia installed from snap

-> % olivia   
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Fontconfig warning: FcPattern object weight does not accept value [40 210)
[1]    15173 segmentation fault (core dumped)  olivia

**Comment by keshavbhatt** [comment]
try what suggested here:  https://github.com/keshavbhatt/BingWall/issues/16

**Comment by AndreiBiziuk** [comment]
Thank You, it worked!
