### ISSUE TITLE
Download of additional files once program has launched for 1st time

### ISSUE THREAD

**Issue by Thesupergrass** [keshavbhatt/olivia#106]
Hi there,

When I launched the program for the 1st time a notification box appeared asking me to download youtube-dl (with modifications). What modifications & where is this file coming from? Is the source available for this modified file?

Thanks

**Comment by keshavbhatt** [comment]
This file comes from my server, it's youtube-dl most of the time. But when youtube-dl is broken or doesn't work as expected I change it to something like ytdlc etc.
