### ISSUE TITLE
Olivia Engine Fails to Download

### ISSUE THREAD

**Issue by KenEkanem** [keshavbhatt/olivia#121]
### Issue:
Olivia is experiencing issues when trying to download its engine based on youtube-dl. The engine is supposed to be 1.4MB in size, but the download process takes forever and doesn't download.

### Expected Behavior:
The Olivia engine should be downloaded successfully without any errors.

### Current Behavior:
When attempting to download the Olivia engine, it takes forever and doesn't download, and users cannot utilize the features.

### Steps to Reproduce:

- Attempt to download the Olivia engine.
- Observe the download process.
- Note any error messages or issues encountered during the download.

### Additional Information:
- Olivia version: 1.2
- Operating System: Xubuntu 22.04.3 LTS

**Comment by keshavbhatt** [comment]
Maybe the issue was temporary, I tried to reproduce this and download finished on time and everything worked as expected. 
Let me know if you are still facing the issue.

**Comment by KenEkanem** [comment]
I removed and reinstalled it, but now it throws an error after running the download for a couple of minutes see image
![Olivia engine download](https://github.com/keshavbhatt/olivia/assets/60167999/719b65ab-a699-4a6a-b0f4-71b82089c77f)

**Comment by KenEkanem** [comment]
Thank you for your response

**Comment by keshavbhatt** [comment]
It seems that your computer is not able to connect to github.com
Can you verify that by opening the website on your web browser?

Thanks

**Comment by KenEkanem** [comment]
Yes. github.com opens on my web browser.

**Comment by keshavbhatt** [comment]
What about this url?

https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp

**Comment by KenEkanem** [comment]
> What about this url?
> 
> https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp

This Works!
