### ISSUE TITLE
Please provide a portable AppImage for Linux, too

### ISSUE THREAD

**Issue by probonopd** [keshavbhatt/olivia#29]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by keshavbhatt** [comment]
yep :)

**Comment by pemartins1** [comment]
Yes please provide an appimage. I want to try Olivia player but there is no way I'll use snaps.
A deb package would also be very welcome.

**Comment by probonopd** [comment]
Please check https://github.com/probonopd/olivia/releases/tag/continuous. It now contains mpv and I think it succeeds in launching mpv, but then it doesn't seem to communicate with it. Why? @keshavbhatt

**Comment by keshavbhatt** [comment]
let me check.

**Comment by keshavbhatt** [comment]
these are errors when olivia tries to call mpv 

`mpv: /tmp/.mount_OliviaVfQvvL/usr/lib/libxkbcommon.so.0: no version information available` `(required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)`

`mpv: relocation error: /usr/lib/x86_64-linux-gnu/libmirclient.so.9: symbol xkb_compose_table_unref,` `version V_0.5.0 not defined in file libxkbcommon.so.0 with link time reference`

**Comment by probonopd** [comment]
Strangely, I don't get those...


```
me@host:~$ /tmp/.mount_OliviaooZLpn/usr/bin/mpv 
mpv git-2019-04-25-71ad1e2 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Jul  7 21:18:27 UTC 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.52.100
   libavformat     58.27.103
   libswscale      5.4.100
   libavfilter     7.50.100
   libswresample   3.4.100
ffmpeg version: git-2019-04-28-3dee6c0

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name
```

Can you try to run `/tmp/.mount_Olivia*/usr/bin/mpv` while the Olivia AppImage is running?

**Comment by keshavbhatt** [comment]
That's clearly due to the lib's version compatibility.one packaged inside appimage is not compatible with the one installed on my system, am on 16.04 . 
Also you can check why mpv is not able to play anything by pressing 'd' in olivia.

**Comment by keshavbhatt** [comment]
this issue never happens in snaps cause all libs required are packaged inside same package nothing is  needed from host system.

**Comment by probonopd** [comment]
All `d` gives me is 

```
Song - 340922090 Already in queue
Song - 340922090 Already in queue
Song - 340922090 Already in queue
```

**Comment by probonopd** [comment]
> this issue never happens in snaps cause all libs required are packaged inside same package nothing is needed from host system.

a.k.a. "bloat" ;-)

**Comment by keshavbhatt** [comment]
tap focus on central widget and press 'd' will show a panel at bottom of olivia's window.

**Comment by probonopd** [comment]
https://github.com/probonopd/olivia/blob/patch-1/mpv.yml is using ingredients from trusty so Ubuntu 14.04 and later should (at least if there are no bugs) be able to run it.

**Comment by keshavbhatt** [comment]
> > this issue never happens in snaps cause all libs required are packaged inside same package nothing is needed from host system.
> 
> a.k.a. "bloat" ;-)

no its nice thing about snaps. that's how we can ensure they will run anywhere.

**Comment by probonopd** [comment]
> tap focus on central widget and press 'd' will show a panel at bottom of olivia's window.

Yes and all this windows gives me is

```
Song - 340922090 Already in queue
Song - 340922090 Already in queue
Song - 340922090 Already in queue
```

**Comment by keshavbhatt** [comment]
whatever an appimage should ensure it will run same on all systems no matter if its 16.04 or 18.04

**Comment by probonopd** [comment]
Yes, and it does, we have a bug here...

**Comment by keshavbhatt** [comment]
i will test appimage on 18.04 in morning tomorrow. ty
