### ISSUE TITLE
No way to add local music from a folder

### ISSUE THREAD

**Issue by wishx** [keshavbhatt/olivia#32]
There doesn't appear to be any way to add music from a folder. I've clicked and right-clicked on every possible part of the application and there simply isn't an option. I get Reload and Inspect, but Local Music and Add New Playlist do nothing.

**Comment by keshavbhatt** [comment]
Olivia do not allow adding local music right now that's could be a planned feature which will included on future, currently you find music online in olivia and play it save it and play it back when needed, after this am developing a way by which users will be able to save their music to their account and share it with friends.

**Comment by LukeZBaker** [comment]
I'll be happy to write a review once the ability to play local music is added.

**Comment by keshavbhatt** [comment]
Duplicate of #53
