### ISSUE TITLE
Feature Reques: Import public youtube playlists

### ISSUE THREAD

**Issue by sedago** [keshavbhatt/olivia#38]
In most modern media players like VLC you can import existing YouTube playlists.

I would love to see a similar feature in olivia. 
Here Is an example playlist: https://www.youtube.com/playlist?list=PLvCguu7BmkGWlexq4DydR3Eh--om1dStm

**Comment by keshavbhatt** [comment]
Hi, thanks for this feature request ,this feature need design decisions before implementation,
this feature can be revamped if we will add playlist search filter in existing YouTube browser option, and on clicking on any playlist it will list the items it contains which could be added selectively in player queue or with a single button will make all items into the player queue.
