### ISSUE TITLE
[Documentation] Command for running olivia

### ISSUE THREAD

**Issue by Roshanjossey** [keshavbhatt/olivia#39]
In the Readme, command to run Olivia is 

`QT_STYLE_OVERRIDE='gtk' olivia.test.olivia`

But, in my directory structure, I see

> `snap/bin/olivia-test.olivia`

So, when I do 

`QT_STYLE_OVERRIDE="gtk" olivia-test.olivia`, olivia opens up. Is this an error in documentation?

**Comment by keshavbhatt** [comment]
does the command given in readme opens olivia ?? if yes then what the issue recommend :flushed:

**Comment by keshavbhatt** [comment]
oh i got it, i have updated readme.
