### ISSUE TITLE
NOT an issue BUT!

### ISSUE THREAD

**Issue by mrjpeel** [keshavbhatt/olivia#42]
I created a logo a while back for a music app but it never got used.  If you re interested I would love to see your project use it.

Its similar to the one you have.

[screenshot here](http://www.clipular.com/posts/4577321965846528?k=7Ejwi2dGdnR1CG625iipvVX8Wio)

**Comment by keshavbhatt** [comment]
Olivia right now have a beautiful logo already, thanks for your effort. i will consider using it in my future apps asking you. thanks
