### ISSUE TITLE
archlinux fails to build 

### ISSUE THREAD

**Issue by anibal-aguila** [keshavbhatt/olivia#43]
**archlinux:**

`yay -S olivia --noconfirm `

**Output**
```
Cloning into 'olivia'...
done.
==> Starting pkgver()...
==> Updated version: olivia r273.c40aa93-1
==> Sources are ready.
==> Making package: olivia r273.c40aa93-1 (Fri 24 May 2019 11:55:04 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
Info: creating stash file /home/aa/.cache/yay/olivia/src/olivia/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets
==> ERROR: A failure occurred in build().
    Aborting...
Error making: olivia


```

**Comment by joemarangi** [comment]
#response_container_BBPPID{font-family: Calibri, sans-serif; font-size:12pt; color: #6B46A6;}  Hello I'm really sorry to be sending this but I  never subscribed to this group. How can I stop received threads ?                                                                                                                                                                        Joe Marangi                                                                                                                                                                           From: notifications@github.comSent: 24 May 2019 5:59 pmTo: olivia@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [keshavbhatt/olivia] archlinux fails to build  (#43)  archlinux:
yay -S olivia --noconfirm 
Output
Cloning into 'olivia'...
done.
==> Starting pkgver()...
==> Updated version: olivia r273.c40aa93-1
==> Sources are ready.
==> Making package: olivia r273.c40aa93-1 (Fri 24 May 2019 11:55:04 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
Info: creating stash file /home/aa/.cache/yay/olivia/src/olivia/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets
==> ERROR: A failure occurred in build().
    Aborting...
Error making: olivia

**Comment by keshavbhatt** [comment]
@anibal-aguila olivia need qt with webkit and webkitwidget modules. i think you are using qt which comes with webengine modules.
