### ISSUE TITLE
Equalizer L-R balance not working properly

### ISSUE THREAD

**Issue by deadass0isalive** [keshavbhatt/olivia#45]
Hi there! i found a bug in L-R balance-
When i set L to (0.1) "sound in right ear plug instantly goes up and dropped minimum in left ear plug".
Same Issue when i set R to (0.1).
find attachment.
![olivia_issue_eq](https://user-images.githubusercontent.com/46918309/60768133-fed3fb80-a0de-11e9-8441-3eba17bb1087.png)
![ollivia_issue_eq1](https://user-images.githubusercontent.com/46918309/60768140-0c898100-a0df-11e9-9e97-b5081b26cd3f.png)

**Comment by keshavbhatt** [comment]
i got you, fix coming soon.
