### ISSUE TITLE
Add right-click -> Download

### ISSUE THREAD

**Issue by probonopd** [keshavbhatt/olivia#54]
Please add right-click -> Download.

**Comment by keshavbhatt** [comment]
where ??

**Comment by probonopd** [comment]
On a search result (song)

**Comment by keshavbhatt** [comment]
yes i will implement a feature to download video and then i will integrate this to the same. Ty for suggestion.

**Comment by probonopd** [comment]
And audio only. :+1:

**Comment by keshavbhatt** [comment]
yes both :100:

**Comment by keshavbhatt** [comment]
do you know olivia download songs while buffering them already ?? check in settings and turn on option save track while buffering

**Comment by probonopd** [comment]
Since the built-in player is not working for me, I cannot use that I guess

**Comment by keshavbhatt** [comment]
try snap version or build app from source.
