### ISSUE TITLE
Not working in an Ubuntu Wayland session (works in Gnome session)

### ISSUE THREAD

**Issue by espmartin** [keshavbhatt/olivia#55]
On Ubuntu 19.04, logging into a gnome session, Olivia works flawlessly. In a Wayland session, I get the following error:
---------------------------------------------------------------------------------------------------------
:~$ olivia-test.olivia 
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
---------------------------------------------------------------------------------------------------------
I have tried reinstalling, but same results. Any thoughts on when support will be available for this?

Best Regards,
Martin

**Comment by keshavbhatt** [comment]
hey thanks for reporting this, i will look into this, seems like i have to recompile qt with wayland-egl platform plugin support.

**Comment by keshavbhatt** [comment]
reinstalling application will not help cause runtime is lavking wayland-egl support.

**Comment by espmartin** [comment]
Thank you for the reply! I look forward to using this in my Wayland sessions (I've found Wayland a faster environment than Gnome...)

**Comment by lwille** [comment]
after reading https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055, I found that I can just start Olivia by running `DISABLE_WAYLAND=1  olivia-test.olivia`

**Comment by keshavbhatt** [comment]
did it worked that way in wayland session ?

**Comment by lwille** [comment]
Uhhh, my system summary reports Gnome, but I was getting the `wayland-egl` error before:

![Screenshot from 2019-08-22 15-07-09](https://user-images.githubusercontent.com/175639/63517109-9e621780-c4ee-11e9-801f-5ac7fff869cf.png)

**Comment by keshavbhatt** [comment]
can you test it with DISABLE_WAYLAND=1  olivia-test.olivia  in wayland session ?

**Comment by lwille** [comment]
@keshavbhatt 

![Screenshot from 2019-08-22 18-45-12](https://user-images.githubusercontent.com/175639/63533410-07588800-c50d-11e9-806a-c11354175c9d.png)

**Comment by lwille** [comment]
@keshavbhatt 

![Screenshot from 2019-08-22 18-46-14](https://user-images.githubusercontent.com/175639/63533458-2525ed00-c50d-11e9-876a-dbf75ba5fef7.png)

**Comment by keshavbhatt** [comment]
using command below make it work for now. this command will be included in new builds. ty
DISABLE_WAYLAND=1 olivia-test.olivia
