### ISSUE TITLE
Add to favorite not working

### ISSUE THREAD

**Issue by abuakram** [keshavbhatt/olivia#56]
A very nice app indeed...
But adding radio channels to favorite doesn't work...

It would be nice if you can add the local music folder's path to the app.

thanks

**Comment by keshavbhatt** [comment]
channels can be added to fav in latest build, how you installed app ? do an update. local music folder feature is coming soon, m working on it.

**Comment by logix2** [comment]
Btw this doesn't work for me either. I installed Olivia today from the Snap Store (package olivia; I had olivia-test installed, but I removed it today; didn't use it in a long time).

**Comment by keshavbhatt** [comment]
olivia engine (youtube-dl) is having some issues today in parsing youtube videos. so please wait till it is fixed, everything will work fine again.

**Comment by keshavbhatt** [comment]
fixed try olivia now. :)

**Comment by logix2** [comment]
I think you wanted to reply to the other bug report: https://github.com/keshavbhatt/olivia/issues/59 Indeed that's fixed, thank you!
