### ISSUE TITLE
Items in the filter queue start very very slowly

### ISSUE THREAD

**Issue by dido-b** [keshavbhatt/olivia#72]
What a nice app! 

One trouble: items in the filter queue start extremely slow. Items in the Smart playlist however start almost immediately. 

Below the lines I get in the Help panel when starting (after one or two minutes):

--2019-11-27 12:42:05--  https://r6---sn-h0jeen76.googlevideo.com/videoplayback?expire=1574876515&ei=A2HeXd71D5OA8gOC1YXIBg&ip=80.110.100.203&id=o-AMjKLPZ5LK_RmXIqYnXjIxn5yi_SOXgNzSLI0Iayqnu7&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-h0jeen76%2Csn-4g5edned&ms=au%2Conr&mv=m&mvi=5&pl=17&gcr=at&initcwndbps=2045000&mime=audio%2Fwebm&gir=yes&clen=4905872&dur=269.201&lmt=1518942295583516&mt=1574854841&fvip=6&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAP_YHLW8SAEbZ3Suufd4AKoD4H-U7L9yW37qV1B1CMlMAiEAkUa-G6Vd-EMKtg5EiVSxCbVoS73y5FQJaySsTTNaKhs%3D&sig=ALgxI2wwRQIhAKiAZJ7vjWxVG63_ySNIIjK0gqJ1Jdfeyg7ePr0RdTxWAiBnBFgNz946ktKgSFuEOyJjoWuVP5EZMRby3xzXr473Dw==&ratebypass=yes
Resolving r6---sn-h0jeen76.googlevideo.com (r6---sn-h0jeen76.googlevideo.com)... [file] Reading from stdin...
2a00:1450:4021:2::c, 173.194.163.124
Connecting to r6---sn-h0jeen76.googlevideo.com (r6---sn-h0jeen76.googlevideo.com)|2a00:1450:4021:2::c|:443... 
failed: Connection timed out.
Connecting to r6---sn-h0jeen76.googlevideo.com (r6---sn-h0jeen76.googlevideo.com)|173.194.163.124|:443... 
connected.
HTTP request sent, awaiting response... 302 Found
Location: https://r6---sn-4g5edned.googlevideo.com/videoplayback?expire=1574876515&ei=A2HeXd71D5OA8gOC1YXIBg&ip=80.110.100.203&id=o-AMjKLPZ5LK_RmXIqYnXjIxn5yi_SOXgNzSLI0Iayqnu7&itag=251&source=youtube&requiressl=yes&gcr=at&mime=audio%2Fwebm&gir=yes&clen=4905872&dur=269.201&lmt=1518942295583516&fvip=6&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAKiAZJ7vjWxVG63_ySNIIjK0gqJ1Jdfeyg7ePr0RdTxWAiBnBFgNz946ktKgSFuEOyJjoWuVP5EZMRby3xzXr473Dw==&ratebypass=yes&redirect_counter=1&cm2rm=sn-h0jes7d&req_id=990961d5048ea3ee&cms_redirect=yes&mm=34&mn=sn-4g5edned&ms=ltu&mt=1574855015&mv=m&mvi=5&pl=17&lsparams=mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAJcqdWghd2k_AYHgSqcMN5OYlN7KP4KROgieZxZpiAfoAiAwFMz-XjAO2ZDTl0-QKdyGtNBUS3CUyLM3byhOMzxILg== [following]
--2019-11-27 12:44:16--  https://r6---sn-4g5edned.googlevideo.com/videoplayback?expire=1574876515&ei=A2HeXd71D5OA8gOC1YXIBg&ip=80.110.100.203&id=o-AMjKLPZ5LK_RmXIqYnXjIxn5yi_SOXgNzSLI0Iayqnu7&itag=251&source=youtube&requiressl=yes&gcr=at&mime=audio%2Fwebm&gir=yes&clen=4905872&dur=269.201&lmt=1518942295583516&fvip=6&keepalive=yes&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAKiAZJ7vjWxVG63_ySNIIjK0gqJ1Jdfeyg7ePr0RdTxWAiBnBFgNz946ktKgSFuEOyJjoWuVP5EZMRby3xzXr473Dw==&ratebypass=yes&redirect_counter=1&cm2rm=sn-h0jes7d&req_id=990961d5048ea3ee&cms_redirect=yes&mm=34&mn=sn-4g5edned&ms=ltu&mt=1574855015&mv=m&mvi=5&pl=17&lsparams=mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAJcqdWghd2k_AYHgSqcMN5OYlN7KP4KROgieZxZpiAfoAiAwFMz-XjAO2ZDTl0-QKdyGtNBUS3CUyLM3byhOMzxILg==
Resolving r6---sn-4g5edned.googlevideo.com (r6---sn-4g5edned.googlevideo.com)... 
2a00:1450:4001:52::c, 173.194.164.172
Connecting to r6---sn-4g5edned.googlevideo.com (r6---sn-4g5edned.googlevideo.com)|2a00:1450:4001:52::c|:443... 
failed: Connection timed out.
Connecting to r6---sn-4g5edned.googlevideo.com (r6---sn-4g5edned.googlevideo.com)|173.194.164.172|:443... 
connected.

HTTP request sent, awaiting response... 
200 OK
Length: 4905872 (4,7M) [audio/webm]
Saving to: ‘STDOUT’

     0K .......... .....
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)

AO: [pulse] 48000Hz stereo 2ch float

..... .......... .
......... .......
...  1% 1,02M 5s
    50K .....
..... ...

**Comment by keshavbhatt** [comment]
as the log says, first the link was redirected to another link( which takes some time to resolve ), other than that we can see lot of connection timeout messages (might be due to poor connectivity to internet). the source url are all hosted on google servers which are faster i asume and 99.9% of time are up. 
redirection and new url resolution happens very fast on faster connections. I personally don't find any lag like this. i can write my own URL resolver but cannot help with the connection timeout issue.
