### ISSUE TITLE
Support system-provided youtube-dl

### ISSUE THREAD

**Issue by luigino** [keshavbhatt/olivia#73]
At least as build option, it can get complicated for linux packagers otherwise.

**Comment by keshavbhatt** [comment]
system youtube-dl is not always up to date, olivia will fail to get track url in case user will be having older version. of youtube-dl.

**Comment by keshavbhatt** [comment]
> At least as build option, it can get complicated for linux packagers otherwise.

Olivia take care of youtube-dl itself just add python as dependency.
