### ISSUE TITLE
Soundcloud integration

### ISSUE THREAD

**Issue by c1Koriginal** [keshavbhatt/olivia#75]
I discovered Olivia something like a month ago and this is the best player for linux I have seen so far with functionality of getting the music from somewhere else than it's own library.
I honestly don't know if this is the direction you want to move in, however it would be great if you created a soundcloud integration.

**Comment by keshavbhatt** [comment]
Soundcloud intitial integration is in master now :) 
users can search, and browse top tracks from soundcloud now. more features coming soon.

**Comment by keshavbhatt** [comment]
Soundcloud intitial integration is in master now :) 
users can search, and browse top tracks from soundcloud now. more features coming soon.
