### ISSUE TITLE
Please provide PPA or DEB package?

### ISSUE THREAD

**Issue by blackoutworm** [keshavbhatt/olivia#78]
Hi there.
I like this player, but I really can't stand Snap.
Could you guys please provide either a PPA or at least a DEB package for us Debian/Ubuntu based distro users?

**Comment by keshavbhatt** [comment]
the problem is with maintaining Olivia as debian package. Olivia uses different packages and their versions to build which are not necessarily available across range of Ubuntu versions. So snap is the preferred one here :) also don't hate snaps they are doing fine.

**Comment by WulftheNordicRanger** [comment]
If a deb package is out of the question,  maybe appimage would be a good compromise? There are many users (myself included) who are on Ubuntu based distros but really don't like snap (needing to create an account to use the GUI installer being one reason). Appimage is also distro agnostic  but does not require one to create an account to use

**Comment by pemartins1** [comment]
Plus one for AppImage and also for deb package. I use an Ubuntu based distro and snaps are simply out of the question. Snaps are really bad.

**Comment by keshavbhatt** [comment]
Maintaining debian rpm and appimage for Olivia right now is time taking task for me, If anyone can help reopen it to discuss.
