### ISSUE TITLE
Building from Source

### ISSUE THREAD

**Issue by krazynez** [keshavbhatt/olivia#79]
Using Pop!_OS 19.10
1.) With using Qt5, I had to change all #include <QtGui/*> to #include <QWidget/*> 
2.) I had to remove all QApplication::UnicodeUTF8 in the same files that produced the first error.
3.) Also had to install libtagc0-dev for #include "taglib/taglib.h" error. Some reason libtag1-dev didn't fix this. Had to use libtagc0-dev

After that, it built and ran perfectly. I just used qmake -qt=qt5 then make $(nproc)

I had to specify Qt5 because of the remnants of Qt4 that were previously installed.

**Comment by keshavbhatt** [comment]
Glad it worked for you :) you need to care about installed mpv version. older version of "mpv" from official repo will not work. ad Olivia uses latest mpv from PPA.

**Comment by krazynez** [comment]
Oh I just used apt and videos work with YouTube playback. Is there anything specific that you know of that won't work so I can try it out?

**Comment by keshavbhatt** [comment]
your qt5 install should have webkit and webkitwidgets modules.

**Comment by krazynez** [comment]
Correct it does, I made sure that they were installed.
