### ISSUE TITLE
Jack Server problem

### ISSUE THREAD

**Issue by chris-corless** [keshavbhatt/olivia#85]
I have been using Olivia for a few weeks now, as a snap.  A couple of days ago I updated to the new version.  Mistakenly, I did this by removing the old snap and reinstalling (I should have just done 'snap refresh').  Now, when I try to play any radio stations I get an error in the debug window:

 (+) Audio --aid=1 (aac 2ch 44100Hz)
File tags:
 icy-title: XXXXXXXXXXXXXXXXXXXXXXXX

ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
[ao/alsa] Playback open error: No such file or directory

[ao/oss] Can't open audio device /dev/dsp: No such file or directory

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel

jack server is not running or cannot be started

JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ao/jack] cannot open server

[ao] Failed to initialize audio driver 'jack'
Could not open/initialize audio device -> no sound.

I'm not sure if this is because I uninstalled and reinstalled, or because of the new version.  I use Linux Mint 19.3.

I attached the alsa.config.

[alsa.conf.txt](https://github.com/keshavbhatt/olivia/files/4216600/alsa.conf.txt)

**Comment by keshavbhatt** [comment]
make sure "audio playback and record" permission is turned on for olivia.
From command line you can enable them like this: 
`snap connect olivia:pulseaudio`
`snap connect olivia:alsa`

**Comment by SalmanTheExorcist** [comment]
> make sure "audio playback and record" permission is turned on for olivia.
> From command line you can enable them like this:
> `snap connect olivia:pulseaudio`
> `snap connect olivia:alsa`

Dear Keshavbhatt,
I've been facing similar issues to what Chris was having. Your suggestion above solved it for me. Thank you very much. Just wanted to confirm that the solution worked and also express my deepest appreciation for a wonderful software (Olivia).
~Sam~

**Comment by keshavbhatt** [comment]
thanks, tbis issue will be completely gone in new update. thanks

**Comment by keshavbhatt** [comment]
commit [#6c6f945](https://github.com/keshavbhatt/olivia/commit/6c6f945a21cc0b3c0a60df6013893a592da03511) fixes this issue. Thanks
