### ISSUE TITLE
Crashes Ubuntu 19.10

### ISSUE THREAD

**Issue by stukev** [keshavbhatt/olivia#87]
I've been trying Olivia for the last 2 days and I've had several crashes to the login mask since. It seems the Kernel doesn't like something it's doing:

> Mar  8 14:20:58 XPS-15-9550 kernel: [1554809.773442] audit: type=1400 audit(1583673658.882:397781): apparmor="DENIED" operation="open" profile="snap.olivia.olivia" name="/etc/mpv/encoding-profiles.conf" pid=9473 comm="mpv" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Mar  8 14:20:58 XPS-15-9550 kernel: [1554809.773447] audit: type=1400 audit(1583673658.882:397782): apparmor="DENIED" operation="open" profile="snap.olivia.olivia" name="/etc/mpv/mpv.conf" pid=9473 comm="mpv" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Mar  8 14:20:59 XPS-15-9550 kernel: [1554809.934224] audit: type=1400 audit(1583673659.042:397783): apparmor="DENIED" operation="open" profile="snap.olivia.olivia" name="/etc/pulse/client.conf.d/" pid=9473 comm="mpv" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Mar  8 14:21:43 XPS-15-9550 kernel: [1554854.800990] rfkill: input handler enabled
> Mar  8 14:21:47 XPS-15-9550 kernel: [1554858.163933] rfkill: input handler disabled
>

**Comment by keshavbhatt** [comment]
give audio-playback permission to olivia.

**Comment by keshavbhatt** [comment]
@stukev There is nothing in olivia that a kernel won't like, those log you are looking at are from apparmor(snapd uses for sandboxing apps) those denials are common and caused if required permissions are not given to app.
