### ISSUE TITLE
Plays another song instead of the indicated song.

### ISSUE THREAD

**Issue by eedeidk** [keshavbhatt/olivia#91]
Plays some weird song instead of the searched song on the default tracks section. Sometimes if searched on youtube  the same happens. Like I was trying to play *guzarish* from *ghajini*, 
![Screenshot from 2020-05-02 07-20-37](https://user-images.githubusercontent.com/59429783/80852347-74e4b880-8c45-11ea-817a-66f324318b56.png)
well it shows the song tag but on playing it is some different song. Like this there are some songs. I tried clearing data etc. but seems not to work.
 Well I am on ubuntu focal fossa, I installed Olivia from snap store.

**Comment by keshavbhatt** [comment]
I don't get that, can you make a little GIF or Video to show what exactly is happening ?

**Comment by eedeidk** [comment]
`https://giphy.com/gifs/ek3vKO0wRSKN6fbuBY/html5`
I attached this. the first song being played is not the song it shows. When I tried playing after a serach on youtube it is the REAL song. I don't know what's causing this. But there are many more like this one.

**Comment by keshavbhatt** [comment]
I tried same two songs and both of them plays correct songs for me.
