### ISSUE TITLE
backup and restore does not work

### ISSUE THREAD

**Issue by cyrilhicks** [keshavbhatt/olivia#94]
I get a warning that backup does not work and should be referred to you.

**Comment by keshavbhatt** [comment]
How you installed olivia ? 
Snap package is the preferred way. 

If you installed with other methods please mention to get this resolved.

**Comment by cyrilhicks** [comment]
I installed it from github site by clicking on install.  I do not know how to use the snap way.




CYRIL ...like the night breeze...seldom seen, but always felt!...

"when your work speaks for itself, learn to shut up!"



1. Men and women are being scammed for "love" everyday, I was!  
DO NOT SEND MONEY TO STRANGERS, EVEN IF YOU HAVE BEEN CHATTING FOR SOME MONTHS!
Don't be a victim, check this site for your email/IM friend first, to see if they are listed as scammers already.   Many scammers use the same phony pictures!
 Go to: http://www.stop-scammers.com


2. What's the latest gossip, virus, "freebie", save somebody by sending postcards around the world???  Before you embarrass yourself and your credibility, check it out at: www.snopes.com  find if it's a hoax or real! 

    On Monday, July 27, 2020, 9:17:49 AM GMT-5, Keshav Bhatt <notifications@github.com> wrote:  
 
 


How you installed olivia ?
Snap package is the preferred way.

If you installed with other methods please mention to get this resolved.

**Comment by keshavbhatt** [comment]
what is the output of `snap info olivia` ?

**Comment by keshavbhatt** [comment]
You can install Olivia with `snap install olivia`
Which as I tested backup and restore feature works fine.

**Comment by cyrilhicks** [comment]
ok, thanks

CYRIL ...like the night breeze...seldom seen, but always felt!...

"when your work speaks for itself, learn to shut up!"



1. Men and women are being scammed for "love" everyday, I was!  
DO NOT SEND MONEY TO STRANGERS, EVEN IF YOU HAVE BEEN CHATTING FOR SOME MONTHS!
Don't be a victim, check this site for your email/IM friend first, to see if they are listed as scammers already.   Many scammers use the same phony pictures!
 Go to: http://www.stop-scammers.com


2. What's the latest gossip, virus, "freebie", save somebody by sending postcards around the world???  Before you embarrass yourself and your credibility, check it out at: www.snopes.com  find if it's a hoax or real! 

    On Friday, July 31, 2020, 10:19:36 AM GMT-5, Keshav Bhatt <notifications@github.com> wrote:  
 
 


You can install Olivia with snap install olivia
Which as I tested backup and restore feature works fine.
