### ISSUE TITLE
Fontconfig warning: FcPattern object weight does not accept value [0 205)

### ISSUE THREAD

**Issue by LouBerry** [keshavbhatt/olivia#95]
Wanted to try Olivia snap package latest version on manjaro 

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.4.44-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8565U CPU @ 1.80GHz
Memory: 15,5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

Won't start with message: 

```
Fontconfig warning: FcPattern object weight does not accept value [0 205)
Segmentation fault (core dumped)
```
Any idea, what could cause this issue.

**Comment by keshavbhatt** [comment]
try to delete ~/snap/olivia and restart app.

**Comment by LouBerry** [comment]
already tried, doesn't change, reinstall same issue

**Comment by keshavbhatt** [comment]
try this this issue is with system font cache and not with application. 
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4551#issuecomment-567012959

**Comment by LouBerry** [comment]
alright...
tried the what you mentioned without success, so I build the project from source and this works just fine

It seems that I have a specific problem with snap packages, other snap apps having issues with fonts as well, like just displaying blocks instead of letters.

So not really solved but I think we can close here.

**Comment by montvid** [comment]
to fix the crash do:

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
run olivia

**Comment by orimdominic** [comment]
@montvid Thank you very much for the solution.
After installing some fonts from [cancng/fonts](https://github.com/cancng/fonts), my VLC mediaplayer was not starting and I was getting the error
```bash
VLC media player 3.0.18 Vetinari (revision 3.0.18-0-ge9eceaed4d)
[00005594cf2b6b40] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Qt: Session management error: Could not open network socket
Fontconfig warning: FcPattern object weight does not accept value [50 200)
[1]    19716 segmentation fault (core dumped)  vlc
```
whenever I run the `vlc` command.

Your solution fixed it for me 🙌🏽 
Just putting this here for someone else

**Comment by danielricecodes** [comment]
Googled a 

> to fix the crash do:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```
> 
> run olivia

This worked for me after googling a `vlc` related issue on Ubuntu 23.10 (Mantic).

```
~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
~ $ vlc --version
VLC media player 3.0.19 Vetinari (revision 3.0.19-0-g32b50de2a2)
```

Now VLC opens again no problems :tada:

**Comment by oldzoomer-ru** [comment]
> to fix the crash do:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```
> 
> run olivia

Now Snap VLC is working on my Fedora 40 Workstation :)

**Comment by julian-alarcon** [comment]
Related: https://github.com/electron-userland/electron-builder/issues/5217

**Comment by SKShanthakumar** [comment]
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r

how does this fix work? what went wrong and how does this fix the issue?

**Comment by rodnye** [comment]
> to fix the crash do:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```
> run olivia 

Tested on Kubuntu 24.04 and working fine! Thanks!

**Comment by amircitoedu** [comment]
I experienced the same issue. It was resolved by running the commands shared previously.
