### ISSUE TITLE
cant run it on debian buster (kde plasma)

### ISSUE THREAD

**Issue by Dinex-dev** [keshavbhatt/olivia#98]
i cant run it on Debian buster with kde plasma desktop environment 

installed it from snapstore

**Comment by keshavbhatt** [comment]
what is output when you try to run app from terminal ? 

`snap run olivia` or `olivia`

**Comment by Dinex-dev** [comment]
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Store not Open , opening...
Store open for queries "/home/dinex/snap/olivia/127/.local/share/org.keshavnrj.ubuntu/Olivia/storeDatabase/hjkfdsll/hjkfdsll.db"
Segmentation fault
```

**Comment by keshavbhatt** [comment]
I do not have debian buster vut i will try to test the issue. Thanks for reporting.

**Comment by Dinex-dev** [comment]
ok so i tried to run it with sudo it started but YouTube search is not working

[working with sudo image](https://www.imgurupload.com/uploads/20201125/d2a624b5bca21d4f04979893daee1ead86b57adb.png)

[YouTube search not working image](https://www.imgurupload.com/uploads/20201125/bfdc5595244bd505f89977c9b683ef2f66eeda78.png)

**Comment by keshavbhatt** [comment]
This is temporary and will be back soon.

**Comment by Dinex-dev** [comment]
Ohk thanks
