### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by webmastak** [keshavbhatt/olivia#99]
Minimize to tray when the window is closed. Is there such a function?

**Comment by keshavbhatt** [comment]
Will add that in next update. thanks

**Comment by webmastak** [comment]
Tell me why the Playlists button is not active?
Also, for any request in the YouTube Playlists, it does not find anything.

**Comment by keshavbhatt** [comment]
Playlist feature is not implemented yet, Youtube playlists search used to work before but its no longer working. will fix it later. ty

**Comment by webmastak** [comment]
Another strange bug. If you set the app transperancy to 95, the next time you start the application, the app transperancy is 100, although in the config file `appTransperancy=95` have to change the settings manually to 95

**Comment by keshavbhatt** [comment]
ty will fix these soon.

**Comment by keshavbhatt** [comment]
commit f0461be closes this.

**Comment by webmastak** [comment]
Thanks. But it would not be bad for the tray icon to be shown only if the item is selected in the settings - switch to tray. 
If the item is selected in the settings - close the application, then the tray icon is not displayed.

**Comment by keshavbhatt** [comment]
In near updates. thanks

**Comment by webmastak** [comment]
And if it's to add to minimize / maximize the application by clicking the LMB icon in the tray. 
And not through the context menu by RMB.
